#!/usr/bin/env node
// Turn TTS alignment into composition timing.
//   node prep.mjs <project-dir>
// Reads  <project>/sound.json            { tempo, voStart, tail }
//        <project>/assets/audio/cues.json, words.json
// Writes <project>/timing.js  → window.TIMING = { CUES, WORDS, TEMPO, VO_START, SPEECH_END, DURATION }
//
// Every narration time is divided by `tempo` (the mix time-stretches the voice
// by the same factor) and shifted by `voStart`, so visuals and audio share one clock.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const dir = process.argv[2];
if (!dir) throw new Error("usage: prep.mjs <project-dir>");
const sound = JSON.parse(readFileSync(join(dir, "sound.json"), "utf8"));
const cues = JSON.parse(readFileSync(join(dir, "assets/audio/cues.json"), "utf8"));
const words = JSON.parse(readFileSync(join(dir, "assets/audio/words.json"), "utf8"));
const { tempo = 1, voStart = 0.5, tail = 3.5 } = sound;

const t = (s) => Number((s / tempo + voStart).toFixed(3));
const CUES = Object.fromEntries(Object.entries(cues).map(([k, v]) => [k, t(v)]));
const WORDS = words.map((w) => ({
  w: w.text.toLowerCase().replace(/[^a-z0-9.#/]/g, "").replace(/\.$/, ""),
  s: t(w.start),
  e: t(w.end),
}));
const SPEECH_END = WORDS.at(-1).e;
const DURATION = Math.ceil((SPEECH_END + tail) * 10) / 10;

const out = `// Generated by video-lab/scripts/prep.mjs — do not edit by hand.
window.TIMING = ${JSON.stringify({ TEMPO: tempo, VO_START: voStart, SPEECH_END, DURATION, CUES, WORDS })};
`;
writeFileSync(join(dir, "timing.js"), out);

// The root and soundtrack lengths are static attributes the renderer reads at
// compile time, so stamp the narration-derived duration onto both.
const html = join(dir, "index.html");
if (existsSync(html)) {
  const src = readFileSync(html, "utf8");
  const stamped = src.replace(/<(div|audio)\b[^>]*\bid="(root|soundtrack)"[^>]*>/g, (tag) =>
    tag.replace(/data-duration="[\d.]+"/, `data-duration="${DURATION}"`),
  );
  if (stamped !== src) writeFileSync(html, stamped);
}
console.log(JSON.stringify({ SPEECH_END, DURATION, cues: Object.keys(CUES).length, words: WORDS.length }));
